#!/bin/bash
set -e -x

# Mounting cgroupfs
/usr/bin/cgroupfs-mount

# Starting docker daemon
(/usr/bin/dockerd -H unix://)&
DOCKER_PID=$!

airgap_image_file='scripts/airgap/image-list.txt'
images=$(cat "${airgap_image_file}")
xargs -n1 docker pull <<< "${images}"
docker save ${images} -o dist/artifacts/docker-images.tar

kill -9 ${DOCKER_PID}
